site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and framework'
repo_url: https://github.com/gabrielmelogm/node-example
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
    - Getting started: 'docs/index.md'