redis-ha:
  enabled: true

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationset:
  replicas: 1

global:
  domain: argocd.test.com

certificate:
  enabled: true

server:
  replicas: 1
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: nginx
    tls: true